name: Experiment GitHub Action 1
description: An experimental GitHub Action.

inputs:
  input-string:
    description: The input string will be compared against the desired string in the binary.
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Check out revision
      uses: actions/checkout@v2
      with:
        repository: tcsnfkx/actions
        path: tcsnfkx_actions

    - name: Check GitHub Workspace 1
      shell: bash
      run: |
        echo "Workspace dir:"
        echo "${{ github.workspace }}"
        tree ${{ github.workspace }}

    - name: Bazel build experiment action 1.
      shell: bash
      run: |
        cd ./tcsnfkx_actions
        bazel build -c opt //src/main/experiment_action_1:experiment_action_1
        cd ..

    - name: Check GitHub Workspace 2
      shell: bash
      run: |
        echo "Workspace dir:"
        echo "${{ github.workspace }}"
        tree ${{ github.workspace }}

    - name: Run experiment action 1.
      shell: bash
      run: ${{ github.workspace }}/tcsnfkx_actions/bazel-bin/src/main/experiment_action_1/experiment_action_1 --input=${{ inputs.input-string }}
